<?php

namespace common\widgets;

use Yii;
use yii\base\Widget;
use yii\web\HttpException;
use common\models\Comments;
use yii\helpers\Html;

class CommentsWidget extends Widget
{
    public $model;

    public function init()
    {
        parent::init();
        if (is_null($this->model))
        {
            throw new HttpException(500, 'پست مربوطه را مشخص نکرده اید');
        }
    }
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $this->showComments();
    }

    function showComments()
    {
        $comments= Comments::find()->orderBy('id DESC')->where(['post_id' => $this->model->id, 'active' => 1])->all();
        foreach ($comments as $comment)
        {
            echo '<div class="well well-sm">' . PHP_EOL;
            echo '<p><strong>'. Html::encode($comment->name).'</strong></p>'. PHP_EOL;
            echo '<p>'.Yii::$app->tools->safe($comment->content).'</p>'. PHP_EOL;
            echo '</div>'. PHP_EOL;
        }
    }
}